<?php

return [
    'organization' => [
        'id' => 'org-turtle-tech',
        'name' => 'Turtle Tech',
        'login_email' => 'turtle.rawalpindi@blockbug.test',
        'password' => 'Turtle@BlockBug2026',
        'status' => 'active',
        'created_at' => '2026-08-16 12:46:00',
    ],
    'users' => [
        ['id' => 'user-turtle-admin-01', 'name' => 'Ahmed Bilal', 'email' => 'ahmedbilal92@turtletech.com', 'password' => 'TurtleAdmin@2026', 'role' => 'admin', 'status' => 'active', 'avatar' => null],
        ['id' => 'user-turtle-manager-01', 'name' => 'Sana Javed', 'email' => 'sanajaved11@turtletech.com', 'password' => 'TurtleManager@2026', 'role' => 'manager', 'status' => 'active', 'avatar' => null],
        ['id' => 'user-turtle-dev-01', 'name' => 'Hassan Ali', 'email' => 'hassanali.dev@turtletech.com', 'password' => 'TurtleDev1@2026', 'role' => 'developer', 'status' => 'active', 'avatar' => null],
        ['id' => 'user-turtle-dev-02', 'name' => 'Umair Siddiqui', 'email' => 'umair.siddiqui90@turtletech.com', 'password' => 'TurtleDev2@2026', 'role' => 'developer', 'status' => 'active', 'avatar' => null],
        ['id' => 'user-turtle-tester-01', 'name' => 'Zainab Noor', 'email' => 'zainabnoor.pk@turtletech.com', 'password' => 'TurtleTester1@2026', 'role' => 'tester', 'status' => 'active', 'avatar' => null],
        ['id' => 'user-turtle-tester-02', 'name' => 'Danish Mehmood', 'email' => 'danish.mehmood91@turtletech.com', 'password' => 'TurtleTester2@2026', 'role' => 'tester', 'status' => 'active', 'avatar' => null],
    ],
    'projects' => [
        ['id' => 'project-routemate', 'name' => 'RouteMate School Transport', 'description' => 'Small school transport portal for van routes, student pickup lists and parent arrival notifications.', 'project_key' => 'RMT', 'status' => 'active', 'team_size' => 5],
    ],
    'sprints' => [
        ['id' => 'sprint-rmt-01', 'project_id' => 'project-routemate', 'name' => 'Sprint 01', 'goal' => 'Stabilize route setup, driver check-in, pickup lists and parent notifications.', 'status' => 'active', 'start_date' => '2026-08-17', 'end_date' => '2026-08-31', 'created_by' => 'sanajaved11@turtletech.com', 'completed_at' => null],
    ],
    'bugs' => [
        ['id' => 'bug-rmt-001', 'title' => 'Driver check-in remains pending after GPS permission is granted', 'description' => 'Driver check-in does not immediately update after location permission is enabled.', 'status' => 'closed', 'priority' => 'high', 'severity' => 'major', 'project_id' => 'project-routemate', 'sprint_id' => 'sprint-rmt-01', 'reported_by' => 'zainabnoor.pk@turtletech.com', 'assigned_to' => 'hassanali.dev@turtletech.com', 'verification_tester_email' => 'zainabnoor.pk@turtletech.com', 'steps_to_reproduce' => "1. Deny GPS permission\n2. Open driver check-in\n3. Grant permission\n4. Tap check-in", 'expected_result' => 'Driver should be checked in immediately after valid GPS access.', 'actual_result' => 'Status remains pending until the app is reopened.', 'environment' => 'Android 14, Chrome mobile', 'verified_at' => '2026-08-23 12:20:00', 'created_at' => '2026-08-18 09:25:00'],
        ['id' => 'bug-rmt-002', 'title' => 'Parent receives duplicate arrival notification', 'description' => 'Some parents receive two notifications when the van reaches the same route stop.', 'status' => 'resolved', 'priority' => 'medium', 'severity' => 'minor', 'project_id' => 'project-routemate', 'sprint_id' => 'sprint-rmt-01', 'reported_by' => 'danish.mehmood91@turtletech.com', 'assigned_to' => 'umair.siddiqui90@turtletech.com', 'verification_tester_email' => 'danish.mehmood91@turtletech.com', 'steps_to_reproduce' => "1. Start route\n2. Reach assigned stop\n3. Trigger arrival notification", 'expected_result' => 'Parent should receive one arrival notification.', 'actual_result' => 'Two identical arrival notifications are delivered.', 'environment' => 'Android 13/14, Firebase push notifications', 'verified_at' => null, 'created_at' => '2026-08-21 11:40:00'],
        ['id' => 'bug-rmt-003', 'title' => 'Route stop order resets after editing', 'description' => 'Manually reordered route stops return to the old order after editing one stop.', 'status' => 'in-progress', 'priority' => 'high', 'severity' => 'major', 'project_id' => 'project-routemate', 'sprint_id' => 'sprint-rmt-01', 'reported_by' => 'zainabnoor.pk@turtletech.com', 'assigned_to' => 'hassanali.dev@turtletech.com', 'verification_tester_email' => 'zainabnoor.pk@turtletech.com', 'steps_to_reproduce' => "1. Reorder three stops\n2. Save route\n3. Edit one stop\n4. Save again", 'expected_result' => 'Custom stop order should remain saved.', 'actual_result' => 'Stops return to the previous order.', 'environment' => 'Chrome 128, Windows 11', 'verified_at' => null, 'created_at' => '2026-08-24 10:10:00'],
        ['id' => 'bug-rmt-004', 'title' => 'Absent student still appears in pickup list', 'description' => 'Students marked absent in the morning still remain visible on the driver pickup list.', 'status' => 'in-progress', 'priority' => 'high', 'severity' => 'major', 'project_id' => 'project-routemate', 'sprint_id' => 'sprint-rmt-01', 'reported_by' => 'danish.mehmood91@turtletech.com', 'assigned_to' => 'umair.siddiqui90@turtletech.com', 'verification_tester_email' => 'danish.mehmood91@turtletech.com', 'steps_to_reproduce' => "1. Mark student absent\n2. Open driver's morning pickup list\n3. Refresh list", 'expected_result' => 'Absent student should not appear in the active pickup list.', 'actual_result' => 'Absent student remains visible.', 'environment' => 'Android 14, school driver app', 'verified_at' => null, 'created_at' => '2026-08-25 14:35:00'],
        ['id' => 'bug-rmt-005', 'title' => 'Van registration field accepts invalid format', 'description' => 'Vehicle form accepts symbols and excessively long registration values.', 'status' => 'open', 'priority' => 'low', 'severity' => 'minor', 'project_id' => 'project-routemate', 'sprint_id' => 'sprint-rmt-01', 'reported_by' => 'zainabnoor.pk@turtletech.com', 'assigned_to' => null, 'verification_tester_email' => 'zainabnoor.pk@turtletech.com', 'steps_to_reproduce' => "1. Open Add Van form\n2. Enter invalid registration text\n3. Save", 'expected_result' => 'Invalid registration format should be rejected.', 'actual_result' => 'Form saves the invalid value.', 'environment' => 'Chrome 128, Windows 11', 'verified_at' => null, 'created_at' => '2026-08-28 09:55:00'],
        ['id' => 'bug-rmt-006', 'title' => 'Emergency contact button overlaps map on small screens', 'description' => 'Emergency contact action overlaps the route map on narrow Android screens.', 'status' => 'open', 'priority' => 'medium', 'severity' => 'minor', 'project_id' => 'project-routemate', 'sprint_id' => 'sprint-rmt-01', 'reported_by' => 'danish.mehmood91@turtletech.com', 'assigned_to' => null, 'verification_tester_email' => 'danish.mehmood91@turtletech.com', 'steps_to_reproduce' => "1. Open route screen on small Android phone\n2. Expand map\n3. View emergency contact action", 'expected_result' => 'Button should remain outside the map content.', 'actual_result' => 'Button covers the lower-right area of the map.', 'environment' => 'Android 12, 360x800 display', 'verified_at' => null, 'created_at' => '2026-08-29 15:20:00'],
    ],
    'activities' => [
        ['id' => 'activity-turtle-001', 'bug_id' => 'bug-rmt-001', 'type' => 'created', 'user_id' => 'user-turtle-tester-01', 'user_name' => 'Zainab Noor', 'message' => 'Created GPS check-in bug', 'created_at' => '2026-08-18 09:25:00'],
        ['id' => 'activity-turtle-002', 'bug_id' => 'bug-rmt-001', 'type' => 'assigned', 'user_id' => 'user-turtle-manager-01', 'user_name' => 'Sana Javed', 'message' => 'Assigned bug to Hassan Ali', 'created_at' => '2026-08-19 10:40:00'],
        ['id' => 'activity-turtle-003', 'bug_id' => 'bug-rmt-001', 'type' => 'status_changed', 'user_id' => 'user-turtle-dev-01', 'user_name' => 'Hassan Ali', 'message' => 'Changed status to in-progress', 'created_at' => '2026-08-20 13:15:00'],
        ['id' => 'activity-turtle-004', 'bug_id' => 'bug-rmt-001', 'type' => 'status_changed', 'user_id' => 'user-turtle-dev-01', 'user_name' => 'Hassan Ali', 'message' => 'Changed status to resolved', 'created_at' => '2026-08-22 16:05:00'],
        ['id' => 'activity-turtle-005', 'bug_id' => 'bug-rmt-001', 'type' => 'verified', 'user_id' => 'user-turtle-tester-01', 'user_name' => 'Zainab Noor', 'message' => 'Verified GPS check-in fix and closed bug', 'created_at' => '2026-08-23 12:20:00'],
        ['id' => 'activity-turtle-006', 'bug_id' => 'bug-rmt-002', 'type' => 'created', 'user_id' => 'user-turtle-tester-02', 'user_name' => 'Danish Mehmood', 'message' => 'Reported duplicate arrival notifications', 'created_at' => '2026-08-21 11:40:00'],
        ['id' => 'activity-turtle-007', 'bug_id' => 'bug-rmt-002', 'type' => 'assigned', 'user_id' => 'user-turtle-manager-01', 'user_name' => 'Sana Javed', 'message' => 'Assigned bug to Umair Siddiqui', 'created_at' => '2026-08-22 10:25:00'],
        ['id' => 'activity-turtle-008', 'bug_id' => 'bug-rmt-002', 'type' => 'status_changed', 'user_id' => 'user-turtle-dev-02', 'user_name' => 'Umair Siddiqui', 'message' => 'Changed status to in-progress', 'created_at' => '2026-08-24 09:50:00'],
        ['id' => 'activity-turtle-009', 'bug_id' => 'bug-rmt-002', 'type' => 'status_changed', 'user_id' => 'user-turtle-dev-02', 'user_name' => 'Umair Siddiqui', 'message' => 'Changed status to resolved', 'created_at' => '2026-08-27 15:35:00'],
        ['id' => 'activity-turtle-010', 'bug_id' => 'bug-rmt-003', 'type' => 'created', 'user_id' => 'user-turtle-tester-01', 'user_name' => 'Zainab Noor', 'message' => 'Reported route stop ordering issue', 'created_at' => '2026-08-24 10:10:00'],
        ['id' => 'activity-turtle-011', 'bug_id' => 'bug-rmt-003', 'type' => 'assigned', 'user_id' => 'user-turtle-manager-01', 'user_name' => 'Sana Javed', 'message' => 'Assigned bug to Hassan Ali', 'created_at' => '2026-08-25 09:30:00'],
        ['id' => 'activity-turtle-012', 'bug_id' => 'bug-rmt-003', 'type' => 'status_changed', 'user_id' => 'user-turtle-dev-01', 'user_name' => 'Hassan Ali', 'message' => 'Changed status to in-progress', 'created_at' => '2026-08-27 11:05:00'],
        ['id' => 'activity-turtle-013', 'bug_id' => 'bug-rmt-004', 'type' => 'created', 'user_id' => 'user-turtle-tester-02', 'user_name' => 'Danish Mehmood', 'message' => 'Reported absent student pickup issue', 'created_at' => '2026-08-25 14:35:00'],
        ['id' => 'activity-turtle-014', 'bug_id' => 'bug-rmt-004', 'type' => 'assigned', 'user_id' => 'user-turtle-manager-01', 'user_name' => 'Sana Javed', 'message' => 'Assigned bug to Umair Siddiqui', 'created_at' => '2026-08-26 10:45:00'],
        ['id' => 'activity-turtle-015', 'bug_id' => 'bug-rmt-004', 'type' => 'status_changed', 'user_id' => 'user-turtle-dev-02', 'user_name' => 'Umair Siddiqui', 'message' => 'Changed status to in-progress', 'created_at' => '2026-08-28 12:15:00'],
        ['id' => 'activity-turtle-016', 'bug_id' => 'bug-rmt-005', 'type' => 'created', 'user_id' => 'user-turtle-tester-01', 'user_name' => 'Zainab Noor', 'message' => 'Reported van registration validation issue', 'created_at' => '2026-08-28 09:55:00'],
        ['id' => 'activity-turtle-017', 'bug_id' => 'bug-rmt-006', 'type' => 'created', 'user_id' => 'user-turtle-tester-02', 'user_name' => 'Danish Mehmood', 'message' => 'Reported emergency button overlap on small screen', 'created_at' => '2026-08-29 15:20:00'],
    ],
    'comments' => [
        ['id' => 'comment-turtle-001', 'bug_id' => 'bug-rmt-001', 'parent_comment_id' => null, 'user_email' => 'hassanali.dev@turtletech.com', 'user_name' => 'Hassan Ali', 'comment' => 'Permission callback was not refreshing the check-in state. Fix is ready for QA.', 'created_at' => '2026-08-22 16:10:00'],
        ['id' => 'comment-turtle-002', 'bug_id' => 'bug-rmt-003', 'parent_comment_id' => null, 'user_email' => 'hassanali.dev@turtletech.com', 'user_name' => 'Hassan Ali', 'comment' => 'Reproduced after editing a stop. Checking the persisted sort_order values.', 'created_at' => '2026-08-27 11:20:00'],
    ],
    'notifications' => [],
    'audit_logs' => [
        ['actor_type' => 'user', 'actor_id' => 'user-turtle-admin-01', 'actor_role' => 'admin', 'action' => 'PROJECT_CREATED', 'entity_type' => 'project', 'entity_id' => 'project-routemate', 'succeeded' => true, 'metadata' => ['project_name' => 'RouteMate School Transport'], 'ip_address' => '127.0.0.1', 'request_id' => null],
    ],
];
